In [1]:
%load_ext autoreload
%autoreload 2

import sys
import copy
import math
import pickle

#sys.path.append("../../")

import numpy as np
import torch
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import meshio

#import implicitmodules.torch as dm

In [2]:
import os
os.chdir('/home/gris/projects_py3/implicitmodules')

In [3]:
import implicitmodules.torch as dm

In [4]:
torch.set_default_tensor_type(torch.FloatTensor)

dm.Utilities.set_compute_backend('torch')

In [5]:

def eta(dim, device=None):
    cst = 1 / math.sqrt(2)
    if dim == 2:
        return torch.tensor([[[1., 0., 0.], [0., cst, 0.]],
                             [[0., cst, 0.], [0., 0., 1.]]],
                            dtype=torch.get_default_dtype(), device=device)
    elif dim == 3:
        eta = torch.zeros(dim, dim, int(dim*(dim+1)/2))
        for i in range(3):
            eta[i, i, i] = 1.

        eta[0, 1, 3] = cst
        eta[1, 0, 3] = cst
        eta[0, 2, 4] = cst
        eta[2, 0, 4] = cst
        eta[1, 2, 5] = cst
        eta[2, 1, 5] = cst

        return eta.to(device=device)
    else:
        raise NotImplementedError



In [9]:
d= 2
eta2 = eta(d)

In [10]:
eta2.shape

torch.Size([2, 2, 3])

In [11]:
N = 1
K = torch.zeros([N, d,d,d,d,d])

In [13]:
torch.tensordot(torch.transpose(K, 2, 3), eta(dim)).shape

torch.Size([1, 2, 2, 2, 3])

In [14]:
K.shape

torch.Size([1, 2, 2, 2, 2, 2])

In [18]:
eta2[:,:,1]

tensor([[0.0000, 0.7071],
        [0.7071, 0.0000]])

In [20]:
d= 3
eta3 = eta(d)

In [21]:
eta3.shape

torch.Size([3, 3, 6])

In [24]:
eta3[:,:,2]

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 1.]])

In [25]:
print([eta3[:, :, i] for i in range(6)])

[tensor([[1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]), tensor([[0., 0., 0.],
        [0., 1., 0.],
        [0., 0., 0.]]), tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 1.]]), tensor([[0.0000, 0.7071, 0.0000],
        [0.7071, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]]), tensor([[0.0000, 0.0000, 0.7071],
        [0.0000, 0.0000, 0.0000],
        [0.7071, 0.0000, 0.0000]]), tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.7071],
        [0.0000, 0.7071, 0.0000]])]


In [27]:
for i in range(6):
    print(eta3[:,:,i])
    print("="*20)

tensor([[1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 1., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 1.]])
tensor([[0.0000, 0.7071, 0.0000],
        [0.7071, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])
tensor([[0.0000, 0.0000, 0.7071],
        [0.0000, 0.0000, 0.0000],
        [0.7071, 0.0000, 0.0000]])
tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.7071],
        [0.0000, 0.7071, 0.0000]])
